version: '3.8'

services:
  emotion-detection:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount model file for easy updates without rebuilding
      - ./svm_model.pkl:/app/svm_model.pkl:ro
      # Mount logs directory for persistent logging
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    restart: unless-stopped
    networks:
      - emotion-detection-network

networks:
  emotion-detection-network:
    driver: bridge
